package main.java.com.ct5025.scorecards;

public class SnakesGameScorecard extends Scorecard {
    /**
     * The class that collects, contains, and saves the statistics generated by an instance of SnakesGame being played.
     * @author Coskun Demir
     * @version 1.0
     */
    private int numberOfTurns;
    private int laddersClimbed;
    private int snakesFallen;
    private int finalScore;

    /**
     * Constructor that receives statistics from an instance of NoughtsGame being played
     * @param winner    winner of the game
     * @param winnerType    type of winner (human, computer, none)
     * @param timeTaken time taken during the game in seconds
     * @param turns number of turns taken in the game until winner was found
     * @param score the score that won the game
     * @param ladders   number of ladders climbed by players during the game
     * @param snakes    number of snakes fallen by players during the game
     */
    public SnakesGameScorecard(String winner, String winnerType, long timeTaken, int turns,
                               int score, int ladders, int snakes) {
        this.setWinner(winner);
        this.setWinnerType(winnerType);
        this.setTimeTaken(timeTaken);
        this.setNumberOfTurns(turns);
        this.setFinalScore(score);
        this.setLaddersClimbed(ladders);
        this.setSnakesFallen(snakes);
    }

    /**
     * Converts the statistics collected from the game into a concatenated string
     * and calls a function to save to 'scores.txt'
     */
    public void saveScorecard() {
        //Generate string of results
        String results = ("Snakes & Ladders" + "," + this.getWinner() + "," + this.getWinnerType() + "," + Long.toString(this.getTimeTaken())
                + "," + Integer.toString(this.getNumberOfTurns()) + "," + Integer.toString(this.getFinalScore()) + ","
                + Integer.toString(this.getLaddersClimbed()) + "," + Integer.toString(this.getSnakesFallen()));

        //Save file
        this.saveFile(results);
    }

    private int getNumberOfTurns() {
        return numberOfTurns;
    }

    private void setNumberOfTurns(int numberOfTurns) {
        this.numberOfTurns = numberOfTurns;
    }

    private int getLaddersClimbed() {
        return laddersClimbed;
    }

    private void setLaddersClimbed(int laddersClimbed) {
        this.laddersClimbed = laddersClimbed;
    }

    private int getSnakesFallen() {
        return snakesFallen;
    }

    private void setSnakesFallen(int snakesFallen) {
        this.snakesFallen = snakesFallen;
    }

    private int getFinalScore() {
        return finalScore;
    }

    private void setFinalScore(int finalScore) {
        this.finalScore = finalScore;
    }
}