package main.java.com.ct5025.players;

import java.util.ArrayList;

public class Computer extends Player {
    /**
     * Computer is a subclass of Player, and represents a computer player (i.e. a non-human player).
     * @author Coskun Demir
     * @version 1.0
     */
    //Set name for computer player, assigned randomly
    public Computer() {
        this.name = generateName();
    }

    /**
     * Generates an array containing random names for the computer player to use in a game.
     * @return  an array containing random names
     */
    //Generate list of potential names for computer to use
    private ArrayList<String> createNameArray() {
        ArrayList<String> nameList = new ArrayList<>();

        nameList.add("Kerry (Computer)");
        nameList.add("Winston (Computer)");
        nameList.add("Mohammed (Computer)");
        nameList.add("Eva (Computer)");
        nameList.add("Dennis (Computer)");

        return nameList;
    }

    /**
     * Returns a name based on a random element on the array of names generated by the class.
     * @return  a name for the computer player
     */
    //Randomly select name based on name arraylist
    private String generateName() {
        ArrayList<String> nameList = this.createNameArray();

        //Generate random number within bounds of arraylist size
        java.util.Random rnd = new java.util.Random();
        int selector = rnd.nextInt(nameList.size());

        //Pass selected name back to attribute
        return nameList.get(selector);
    }

}
